baseurl: "/kidnes88.github.com"
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]


assets_path: /assets
sass:
    sass_dir: assets/_sass
    #style: :compressed